shamefullyHoist: true
allowBuilds:
    "@parcel/watcher": true
    "@tailwindcss/oxide": true
    "@vercel/speed-insights": true
    esbuild: true
    sharp: true
minimumReleaseAgeExclude:
    - "@pajecawav/yamf@0.0.5 || 0.0.6"
patchedDependencies:
    hono: patches/hono.patch
