shamefullyHoist: true
allowBuilds:
    "@parcel/watcher": true
    "@tailwindcss/oxide": true
    "@vercel/speed-insights": true
    esbuild: true
    sharp: true
patchedDependencies:
    "@takumi-rs/wasm@2.14.0": patches/@takumi-rs__wasm@2.14.0.patch
minimumReleaseAgeExclude:
    - "@pajecawav/yamf@0.0.8"
